import { GoogleGenAI } from "@google/genai";
import { SYSTEM_PROMPT_SINGLE, SYSTEM_PROMPT_MIX, MODEL_NAME } from "../constants";
import { fileToBase64 } from "../utils/imageUtils";
import { GenerationMode } from "../types";

/**
 * Generates an image using the Gemini 3 Pro Image Preview model (Nano Banana Pro).
 * It takes a list of reference images and the generation mode to select the correct hidden prompt.
 */
export const generateImageFromReferences = async (imageFiles: File[], mode: GenerationMode): Promise<string> => {
  try {
    // The API key must be obtained exclusively from the environment variable process.env.API_KEY
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    // Select the appropriate prompt based on the mode
    const systemPrompt = mode === 'single' ? SYSTEM_PROMPT_SINGLE : SYSTEM_PROMPT_MIX;

    // Prepare image parts
    const imageParts = await Promise.all(
      imageFiles.map(async (file) => ({
        inlineData: {
          mimeType: file.type,
          data: await fileToBase64(file),
        },
      }))
    );

    // Prepare text part (Hidden System Prompt)
    const textPart = {
      text: systemPrompt,
    };

    // Combine for contents
    const contents = {
      parts: [...imageParts, textPart],
    };

    // Call the API
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: contents,
      config: {
        // Nano Banana Pro supports imageConfig for resolution control
        imageConfig: {
          aspectRatio: "9:16",
          imageSize: "1K" // "1K" or "2K" or "4K"
        }
      }
    });

    // Extract the generated image
    let generatedImageUrl: string | null = null;

    if (response.candidates && response.candidates.length > 0) {
      const parts = response.candidates[0].content?.parts;
      if (parts) {
        for (const part of parts) {
          if (part.inlineData && part.inlineData.data) {
             // Construct data URL for the image
             generatedImageUrl = `data:image/png;base64,${part.inlineData.data}`;
             break;
          }
        }
      }
    }

    if (!generatedImageUrl) {
      throw new Error("No image was generated by the model. It might have returned only text.");
    }

    return generatedImageUrl;

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};